version: "3.8"  # Use the appropriate version of Docker Compose

services:
  django:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "9002:9002"  # Map port 8000 inside the container to port 9002 on the host
    environment:
      - DJANGO_SETTINGS_MODULE=ai_chatbot_be.settings  # Replace 'backend' with your Django project name
      - DTABASE_URL=postgres://postgres:Intern2024@db:5432/amaz_ai_chatbot

      # - POSTGRES_DB=notesapp
      # - POSTGRES_USER=ki3ani
      # - POSTGRES_PASSWORD=omniman2023
      # - POSTGRES_HOST=db  # This should match the service name defined below
    depends_on:
      - db
    networks:
      - all

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=amaz_ai_chatbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Intern2024
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    networks:
      - all

#  db:
  # image: ai-chatbot
  # volumes:
  #   - postgres_data:/var/lib/postgresql/data/
  # environment:
  #   POSTGRES_DB: postgres
  #   POSTGRES_USER: postgres
  #   POSTGRES_PASSWORD: heongusi22

# volumes:
#   postgres_data:

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"